#ifndef SHAPES_CONFIG_H
#define SHAPES_CONFIG_H

#define WAVEFORM_LEN 15872
#define MFCC_NUM_DCT_OUTPUTS 10
#define MFCC_TIMESTEPS 49
#define MFCC_TOTAL_LENGTH ((MFCC_NUM_DCT_OUTPUTS) * (MFCC_TIMESTEPS))

#endif // SHAPES_CONFIG_H