services:
  dev_container:
    image: stm32h745-ai-nndev
    container_name: stm32h745-ai-nndev
    runtime: nvidia  # For GPU support
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - /home/gergo/workspace/stm32h745-ai/src/nn:/home/$USERNAME/workspace
      - dev_container_bash_history:/commandhistory
    build:
      args:
        USERNAME: $USERNAME
        UID: $UID
        GID: $GID
    # tmp for debug
    stdin_open: true
    tty: true
volumes:
  dev_container_bash_history: