#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define NET_INPUT_SCALE 0.5847029089F
#define NET_INPUT_ZERO_POINT 83

#define M7_INITIALIZES_UART3 0
#define M7_PROVISIONING 0
#define M7_PREPROCESSING 0
#define M7_RUNNING_NET 0

#endif // APP_CONFIG_H